version: '3.3'

services:
  db:
    ports:
      - "5432:5432"

  php:

  flask-api:
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DEBUG=true
    ports:
      - "5000:5000"
    entrypoint: ['flask', 'run', '--host=0.0.0.0']
