version: '3.3'

services:
  db:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_SERVER: "${POSTGRES_SERVER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php-fpm
    restart: always
    depends_on:
      - db
    volumes:
      - './src-php/:/var/www/symfony:rw,cached'

  flask-api:
    build:
      context: ./src-py
    restart: always
    depends_on:
      - db
      - traefik
    volumes:
      - ./src-py/app:/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: "UTF-8"
      DATABASE_URI: "${FLASK_DATABASE_URI}"
      DEBUG: "${FLASK_DEBUG}"
    expose:
      - 5000
    entrypoint: [ 'gunicorn',  '--config',  'gunicorn_config.py', 'app:app' ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`${HOST}`)"
      - "traefik.http.routers.flask.entrypoints=web"
      - "traefik.http.routers.flask.middlewares=https_redirect"

      - "traefik.http.routers.flask-secured.rule=Host(`${HOST}`)"
      - "traefik.http.routers.flask-secured.entrypoints=websecure"
      - "traefik.http.routers.flask-secured.tls=true"
      - "traefik.http.routers.flask-secured.tls.certresolver=myresolver"

      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

  traefik:
    image: "traefik:v2.3"
    restart: always
    command:
      - "--log.level=ERROR"
      - "--log.filePath=/traefik/traefik.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=${CA_SERVER}"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik:/traefik"