version: '3'

services:
  db:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_SERVER: db
      POSTGRES_USER: inowas
      POSTGRES_PASSWORD: inowas
      POSTGRES_DB: inowas
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - './src-php/:/var/www/symfony:rw,cached'

  api:
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    volumes:
      - './src-php/:/var/www/symfony:ro'

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - api
    ports:
      - "80:80"

