version: '3'

services:
  db:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_SERVER: "${POSTGRES_SERVER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php-fpm
    restart: always
    depends_on:
      - db
    volumes:
      - './src-php/:/var/www/symfony:rw,cached'

  flask-api:
    build:
      context: ./src-py
    restart: always
    depends_on:
      - db
    volumes:
      - ./src-py/app:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - DATABASE_URI=${FLASK_DATABASE_URI}
      - DEBUG=${FLASK_DEBUG}
    command: [ "python", "-u", "app.py" ]
