version: '3.3'

services:
  db:
    image: library/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_SERVER: "${POSTGRES_SERVER}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./docker/database/data:/var/lib/postgresql/data

  php:
    build:
      context: ./docker/php-fpm
    restart: always
    depends_on:
      - db
    volumes:
      - './src-php/:/var/www/symfony:rw,cached'

  flask-api:
    build:
      context: ./src-py
    restart: always
    depends_on:
      - db
    volumes:
      - ./src-py/app:/app
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONIOENCODING: "UTF-8"
      DATABASE_URI: "${FLASK_DATABASE_URI}"
      DEBUG: "${FLASK_DEBUG}"
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask-api.rule=Host(`${HOST}`)"
      - "traefik.http.routers.flask-api.tls=true"
      - "traefik.http.routers.flask-api.tls.certresolver=leresolver"
      - "traefik.port=5000"
    command: [ "python", "-u", "app.py" ]

  traefik:
    image: "traefik:v2.3"
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker"
      - "--api"
      - "--certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.leresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.leresolver.acme.storage=/acme.json"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/traefik/acme.json:/acme.json"
    labels:
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"